---
name: Unit Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
  pull_request:

defaults:
  run:
    shell: sh

jobs:
  unit-tests:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache yarn dependencies
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/.yarnrc.yml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Unit tests
        if: github.ref != 'refs/heads/main'
        run: yarn test
      - name: Unit tests with coverage
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test
          debug: true
